services:
  caddy:
    image: caddy:latest
    container_name: caddy_shared
    environment:
      - PROXY_AUTH_USERNAME=seventrees  # Match your Supabase DASHBOARD_USERNAME
      - PROXY_AUTH_PASSWORD=Seven25!    # Match your Supabase DASHBOARD_PASSWORD
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - seventrees_network
    restart: unless-stopped

  browserless_one:
    image: ghcr.io/browserless/chromium
    container_name: browserless_one
    environment:
      - TOKEN=6R0W53R135510
      - CONCURRENT=10
      - PROXY_HOST=testing.seventrees.nl
      - PROXY_PORT=443
      - PROXY_SSL=true
      - CORS=true
      - HEALTH=true
      - MAX_MEMORY_PERCENT=85
      - MAX_CPU_PERCENT=85
      - TIMEOUT=60000
      - DEBUG=browserless.io:*
    ports:
      - 3000:3000
    networks:
      - seventrees_network
    restart: unless-stopped
    
  browserless_two:
    image: ghcr.io/browserless/chromium
    container_name: browserless_two
    environment:
      - TOKEN=6R0W53R135510
      - CONCURRENT=10
      - PROXY_HOST=testing.seventrees.nl
      - PROXY_PORT=443
      - PROXY_SSL=true
      - CORS=true
      - HEALTH=true
      - MAX_MEMORY_PERCENT=85
      - MAX_CPU_PERCENT=85
      - TIMEOUT=60000
      - DEBUG=browserless.io:*
    ports:
      - 3000:3000      
    networks:
      - seventrees_network
    restart: unless-stopped

networks:
  seventrees_network:
    external: true
    
volumes:
  postgres_data:
  caddy_data:
  caddy_config:

  # caddy-l4:
  #   build:
  #     context: ./caddy-l4          # folder you create below
  #     dockerfile: Dockerfile
  #   container_name: caddy-l4
  #   restart: unless-stopped
  #   environment:
  #     DB_DOMAIN: "testing.seventrees.nl"
  #     ACME_EMAIL: "arvind.nohar@seventrees.nl"
  #   volumes:
  #     - ./caddy-l4/Caddyfile:/etc/caddy/Caddyfile:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - seventrees_network