services:
  postgres:
    image: postgres:15
    container_name: postgres_shared
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Seventrees
      - POSTGRES_DB=users_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # For initialization scripts
    networks:
      - seventrees_network
    restart: unless-stopped

  # caddy:
  #   image: caddy:latest
  #   container_name: caddy_shared
  #   environment:
  #     - PROXY_AUTH_USERNAME=seventrees  # Match your Supabase DASHBOARD_USERNAME
  #     - PROXY_AUTH_PASSWORD=Seven25!    # Match your Supabase DASHBOARD_PASSWORD
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ../Production/app/static:/usr/share/caddy/static/prod  # Adjust path
  #     - ../Testing/app/static:/usr/share/caddy/static/test     # Adjust path
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - seventrees_network
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres

  caddy-l4:
    build:
      context: ./caddy-l4          # folder you create below
      dockerfile: Dockerfile
    container_name: caddy-l4
    restart: unless-stopped
    environment:
      DB_DOMAIN: "testing.seventrees.nl"
      ACME_EMAIL: "arvind.nohar@seventrees.nl"
    volumes:
      - ./caddy-l4/Caddyfile:/etc/caddy/Caddyfile:ro
    # Expose only the TLS-wrapped Postgres listener
    ports:
      - "80:80"
      - "443:443"
    # Attach to the same default network so "supavisor:5432" is resolvable
    networks:
      - seventrees_network

networks:
  seventrees_network:
    external: true

volumes:
  postgres_data:
  caddy_data:
  caddy_config: