services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Seventrees
      - POSTGRES_DB=users_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    

  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../Production/app/static:/usr/share/caddy/static/prod
      - ../Testing/app/static:/usr/share/caddy/static/test
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - postgres
    # Use host networking to reach Windows services
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
  caddy_data:
  caddy_config: